"""Change is_holiday to boolean type

Revision ID: d3e888989659
Revises: 9936b6161a97
Create Date: 2025-05-25 21:37:20.972807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e888989659'
down_revision = '9936b6161a97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('energy_consumption', 'is_holiday',
                   existing_type=sa.INTEGER(),
                   type_=sa.Boolean(),
                   postgresql_using='is_holiday::boolean',
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('energy_consumption', 'is_holiday',
                   existing_type=sa.Boolean(),
                   type_=sa.INTEGER(),
                   postgresql_using='is_holiday::integer',
                   nullable=False)
    # ### end Alembic commands ###
